### ISSUE TITLE
Any news on OpenImmo 2.0 ?

### ISSUE THREAD

**Issue by stell** [ujamii/openimmo#31]
I don't see any news or specifications on this. Any news here?

**Comment by mgrundkoetter** [comment]
I have not seen anything about any new version afer 1.2.7b from 2014 either. If you find something new, feel free to post it here, I will take a look at it. My source for news is their official page: http://www.openimmo.de/go.php/p/44/openimmo-blog.htm

**Comment by stell** [comment]
Last news I got was from February 2021. Supporting members were commenting the beta and till end of March we should get to see official specs. Nothing since then.

**Comment by mgrundkoetter** [comment]
As I am no member I did not even knew that, so thank you for this information. If they publish something new on some internal channel without NDA, you are very welcome to post it here. If the (beta) specs are out, is there a way to publicly view them somewhere?

**Comment by stell** [comment]
Nothing so far. If I get something in my hands, I will let you know.

**Comment by mgrundkoetter** [comment]
2 years have passed, but still nothing new for the 2.0 version of the standard in the public internet. I will close this one. If there will ever be a release, please open a new ticket.
