### ISSUE TITLE
Autoload Classes not Work

### ISSUE THREAD

**Issue by pbreit1988** [ujamii/openimmo#49]
Hello, the composer package not work. After install the Package with composer i not able to load an Xml File.

I get the Following error:

PHP Fatal error: Uncaught Error: Call to a member function deserialize()

I loaded all necessary Scripts via vendor/autoload.php

**Comment by pbreit1988** [comment]
Here is what i have done:

```
mkdir openimmoparser
cd openimmoparser
php7.4 /usr/local/bin/composer req ujamii/openimmo
```

Now i created a file called testfile.php with this content and i put a openimmo sample file in this directory.

Folder Structure:

openimmoparser/vendor -> With the content from the composer
openimmoparser/testfile.php
openimmoparser/single_openimmo_file.xml

This is the content of the testfile.php

```
<?php

require_once('./vendor/autoload.php');

$xmlString = file_get_contents('single_openimmo_file.xml');
/* @var $openImmo \Ujamii\OpenImmo\API\Openimmo */
$openImmo = $serializer->deserialize($xmlString, \Ujamii\OpenImmo\API\Openimmo::class, 'xml');

/* @var $anbieter \Ujamii\OpenImmo\API\Anbieter */
foreach ($openImmo->getAnbieter() as $anbieter) {
    /* @var $immobilie \Ujamii\OpenImmo\API\Immobilie */
    foreach ($anbieter->getImmobilie() as $immobilie) {
        echo PHP_EOL . vsprintf('%s %s, %s %s', [
                $immobilie->getGeo()->getStrasse(),
                $immobilie->getGeo()->getHausnummer(),
                $immobilie->getGeo()->getPlz(),
                $immobilie->getGeo()->getOrt(),
            ]);
    }
}

?>
```

if i run php7.4 testfile.php i get the error. PHP Fatal error: Uncaught Error: Call to a member function deserialize()

**Comment by mgrundkoetter** [comment]
You have not created any serializer in your code, which is what the error message tells you. Try adding
`$serializer = \JMS\Serializer\SerializerBuilder::create()->build();`

**Comment by mgrundkoetter** [comment]
I guess this should be easily fixed by using the code from the docs, so I'll close this one.
