### ISSUE TITLE
xml Reihenfolge

### ISSUE THREAD

**Issue by oioix** [ujamii/openimmo#65]
Hi,
es werden offenbar alle xml-Knoten in alphabetischer Reihenfolge erstellt und zwar egal, in welcher Reihenfolge man die Objekte anlegt und befüllt. 
Ich habe gerade festgestellt, dass ein Portal das xml zuerst nicht geparst hat, weil der Knoten **Uebertragung** erst ganz am am Schluss kommt. 
Also dieser hier:
` <uebertragung art="OFFLINE" modus="NEW" sendersoftware="xyz" senderversion="1.0" techn_email="xyz@xyz.de" timestamp="2022-12-06T20:440:50" umfang="TEIL" version="1.2.7"/>`

Es kam diese Fehlermeldung:
 Umfang: null
- Tech. Email: null
- AnbieterID[ 1xyz / none ] wurde gefunden...
- ERROR: Process konnte nicht ausgefuehrt werden!
- XML: ** Process konnte nicht registriert werden! **

Nachdem die **techn_email** und auch der Umfang **TEIL** ganz klar genannt war, aber nicht erkannt wurde, habe ich den Knoten Uebetragung manuell im Code nach ganz oben vor den Anbieter gestellt und es dann mit der ansonsten gleichen Datei noch einmal probiert. Schließlich wurde das xml mit dieser Reihenfolge-Änderung wie folgt geparst:
- Umfang: TEIL
- Software: xyz
- Version der Software: 1.0
- Tech. Email: xyz@xyz.de

Zumindest dieses Portal scheint also den Knoten **Uebertragung** ganz am Anfang nach `<openimmo>` (also noch vor `<anbieter>`) haben zu wollen. 

Daher meine Frage...
Gibt es eine Möglichkeit die Reihenfolge zu beeinflussen, bzw. das automatische alphabetische Sortieren abzuschalten?

**Comment by mgrundkoetter** [comment]
Die Reihenfolge spielt bei einer XML keine Rolle, da es eine Baumstruktur abbildet, sodass nur die Eltern-Kind-Beziehungen relevant sind. Ich vermute, dass hier etwas nicht korrekt bei der Generierung abgelaufen ist. Am besten wäre, wenn du den Code der das generiert hier mal posten kannst und/oder noch die XML-Datei dazu die erstellt wurde, zumindest Auszüge der relevanten Stellen würden helfen.

**Comment by oioix** [comment]
Vielen Dank für Deine Antwort, aber nein, einen Fehler im Erzeugungscode kann ich 1000% ausschließen. 
Der Code wurde absolut korrekt generiert. Ich habe die einzelnen Ausgaben genau geprüft und zwar im Vergleich mit der xml-Ausgabe einer anderen Software, die einwandfrei funktioniert.

Natürlich weiß ich, dass die Reihenfolge eigentlich keine Rolle spielen sollte, da die Knoten ja benannt sind. Ich vermute, dass der Entwickler des betreffenden Portals das xml in irgendeiner Form in einer for oder foreach-Schleife bearbeitet und die Weiterverarbeitung abbricht, wenn die wesentliche Information zur Übertragung nicht zuerst kommt.
Jedenfalls habe ich die obige Fehlermeldung nicht erfunden. Das ist real life. ;-)

Ich habe es jetzt für mich per workaround inzwischen so gelöst, dass ich das xml nachbearbeite, also die betreffende Zeile Übertragung unten aus dem Code entferne und oben wieder einfüge. So klappt die Übertragung zu dem Portal nun einwandfrei.

Abgesehen von dem Problem mit diesem Portal wäre es auch für die Entwicklung und das debuggen schon ein eheblicher Vorteil, wenn man die Reihenfolge der Ausgabe selbst festlegen könnte, weil es die Vollständigkeits- und Ausgabeprüfung erheblich vereinfachen würde. 
Kann man denn die Reihenfolge irgendwie ändern, bzw. die strikt alphabetische sortierte Ausgabe abschalten?

**Comment by mgrundkoetter** [comment]
Die Reihenfolge wird durch den Serializer bestimmt. Mir ist nicht bekannt, dass man den irgendwie so beeinflussen kann, dass der die Reihenfolge anpasst, aber das macht IMO aber eben auch wenig sinn, da per Definition diese im Format XML keine Relevanz hat. Zum Debuggen ist das leider insgesamt ein ziemlich bescheidenes Format, da kommt man leider um viel manuellen Aufwand auch nicht herum. Falls du was rausfindest kannst du hier gerne einen PR aufmachen, contributions sind sehr willkommen.

**Comment by oioix** [comment]
> Die Reihenfolge wird durch den Serializer bestimmt. Mir ist nicht bekannt, dass man den irgendwie so beeinflussen kann, dass der die Reihenfolge anpasst, aber das macht IMO aber eben auch wenig sinn, da per Definition diese im Format XML keine Relevanz hat. Zum Debuggen ist das leider insgesamt ein ziemlich bescheidenes Format, da kommt man leider um viel manuellen Aufwand auch nicht herum. Falls du was rausfindest kannst du hier gerne einen PR aufmachen, contributions sind sehr willkommen.

Alles klar. 
Hätte ja sein können. ;-) 
Sollte ich auf die Lösung stoßen gebe ich sie natürlich gerne hier bekannt.

**Comment by stell** [comment]
Kannst Du sagen, um welches Portal es sich dabei handelt?

**Comment by oioix** [comment]
Es ist ein kleines Portal. Nennt sich immo4trans.

**Comment by stell** [comment]
Das kenne ich. Einige unserer Kunden exportieren erfolgreich dorthin, aber bei uns ist der node `uebertragung` auch vorne, wobei das wirklich keine Rolle spielen sollte, da das XSD dies nicht  voraussetzt.

**Comment by mgrundkoetter** [comment]
Ich schließe das hier mal, da es kein Fehler in diesem Package ist, sondern eben am Import liegt.

**Comment by oioix** [comment]
> Ich schließe das hier mal, da es kein Fehler in diesem Package ist, sondern eben am Import liegt.

Passt. ;-)
